const SUPABASE_URL = 'https://ppudiemjdvbzshtdjncw.supabase.co';
const SUPABASE_KEY = 'sb_publishable_THTfgODPKTC6drMUJxmFOw_weEls7vu';

let accessToken=null,currentUser=null,shopId=null,products=[],batches=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function daysLeft(date){const t=new Date();t.setHours(0,0,0,0);return Math.ceil((new Date(date+'T00:00:00')-t)/86400000)}
function status(p){const d=daysLeft(p.expiry);if(d<0)return{key:'expired',label:`Expired ${Math.abs(d)}d ago`,cls:'expired'};if(d===0)return{key:'today',label:'Expires today',cls:'dangerText'};if(d<=3)return{key:'3',label:`${d} day${d===1?'':'s'} left`,cls:'dangerText'};if(d<=7)return{key:'7',label:`${d} days left`,cls:'soonText'};return{key:'ok',label:`${d} days left`,cls:'okText'}}
async function request(path,options={}){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json','Prefer':'return=representation',...(options.headers||{})};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers});const text=await r.text();if(!r.ok)throw new Error(text);return text?JSON.parse(text):null}
async function authLogin(email,password){const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||d.msg||'Login failed');return d}
function setView(logged){$('loginView').classList.toggle('hidden',logged);$('appView').classList.toggle('hidden',!logged)}
async function login(){ $('loginError').textContent='';try{const d=await authLogin($('loginEmail').value.trim(),$('loginPassword').value);accessToken=d.access_token;currentUser=d.user;const prof=await request(`profiles?id=eq.${encodeURIComponent(currentUser.id)}&select=shop_id,full_name,role`);if(!prof.length)throw new Error('Your user is not connected to a shop.');shopId=prof[0].shop_id;$('userLabel').textContent=prof[0].full_name||currentUser.email;setView(true);await loadData()}catch(e){$('loginError').textContent=e.message}}
async function loadData(){products=await request(`products?shop_id=eq.${shopId}&active=eq.true&select=*`);const ids=products.map(p=>p.id);batches=ids.length?await request(`batches?product_id=in.(${ids.join(',')})&select=*`):[];render()}
function rows(){return batches.map(b=>{const p=products.find(x=>x.id===b.product_id);return p?{...p,quantity:b.quantity,expiry:b.expiry_date,batchId:b.id}:null}).filter(Boolean)}
function render(){const all=rows(),search=$('search').value.toLowerCase().trim(),sf=$('statusFilter').value,cf=$('categoryFilter').value;const cats=[...new Set(all.map(p=>p.category).filter(Boolean))].sort();$('categoryFilter').innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const expired=all.filter(p=>status(p).key==='expired');const today=all.filter(p=>status(p).key==='today');const within3=all.filter(p=>['today','3'].includes(status(p).key));const within7=all.filter(p=>['today','3','7'].includes(status(p).key));$('allCount').textContent=all.length;$('expiredCount').textContent=expired.length;$('threeCount').textContent=within3.length;$('sevenCount').textContent=within7.length;const alerts=[...expired,...today,...all.filter(p=>['3','7'].includes(status(p).key))].sort((a,b)=>a.expiry.localeCompare(b.expiry));$('alertList').innerHTML=alerts.length?alerts.slice(0,8).map(p=>{const s=status(p);return `<div class="alertItem"><div><strong>${esc(p.name)}</strong><small>${p.quantity} unit${p.quantity==1?'':'s'}${p.shelf_location?` · Shelf ${esc(p.shelf_location)}`:''}</small></div><span class="status ${s.cls}">${s.label}</span></div>`}).join(''):'<div class="noAlerts">✓ No products expire within the next 7 days.</div>';$('alertMore').textContent=alerts.length>8?`+ ${alerts.length-8} more items`:'';const filtered=all.filter(p=>{const s=status(p);return(!search||(p.name+' '+(p.barcode||'')).toLowerCase().includes(search))&&(sf==='all'||s.key===sf)&&(cf==='all'||p.category===cf)}).sort((a,b)=>a.expiry.localeCompare(b.expiry));$('productRows').innerHTML=filtered.map(p=>{const s=status(p);return `<tr><td><strong>${esc(p.name)}</strong><br><small>${esc(p.barcode||'')}${p.shelf_location?` · Shelf ${esc(p.shelf_location)}`:''}</small></td><td>${esc(p.category||'')}</td><td>${p.quantity}</td><td>${new Date(p.expiry+'T00:00:00').toLocaleDateString()}</td><td><span class="status ${s.cls}">${s.label}</span></td><td class="actions"><button onclick="editBatch('${p.batchId}')">✏️</button><button onclick="deleteBatch('${p.batchId}')">🗑️</button></td></tr>`}).join('');$('empty').style.display=filtered.length?'none':'block'}
function openModal(item=null){$('modal').classList.remove('hidden');$('modalTitle').textContent=item?'Edit stock batch':'Add product';$('editId').value=item?.batchId||'';$('name').value=item?.name||'';$('barcode').value=item?.barcode||'';$('category').value=item?.category||'';$('quantity').value=item?.quantity??'';$('expiry').value=item?.expiry||'';$('location').value=item?.shelf_location||'';$('scanNote').textContent=''}
function closeModal(){$('modal').classList.add('hidden')}
$('addBtn').onclick=()=>openModal();$('closeBtn').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};$('loginBtn').onclick=login;$('loginPassword').onkeydown=e=>{if(e.key==='Enter')login()};$('logoutBtn').onclick=()=>{accessToken=null;currentUser=null;shopId=null;products=[];batches=[];setView(false)};$('search').oninput=render;$('statusFilter').onchange=render;$('categoryFilter').onchange=render;
$('productForm').onsubmit=async e=>{e.preventDefault();try{const batchId=$('editId').value;const payload={name:$('name').value.trim(),barcode:$('barcode').value.trim(),category:$('category').value.trim(),shelf_location:$('location').value.trim()};if(batchId){const old=batches.find(b=>b.id===batchId);await request(`products?id=eq.${old.product_id}`,{method:'PATCH',body:JSON.stringify(payload)});await request(`batches?id=eq.${batchId}`,{method:'PATCH',body:JSON.stringify({quantity:Number($('quantity').value),expiry_date:$('expiry').value})})}else{const ps=await request('products',{method:'POST',body:JSON.stringify({...payload,shop_id:shopId})});await request('batches',{method:'POST',body:JSON.stringify({product_id:ps[0].id,quantity:Number($('quantity').value),expiry_date:$('expiry').value})})}closeModal();await loadData()}catch(e){alert('Could not save: '+e.message)}};
window.editBatch=id=>openModal(rows().find(p=>p.batchId===id));window.deleteBatch=async id=>{if(!confirm('Delete this stock batch?'))return;try{await request(`batches?id=eq.${id}`,{method:'DELETE'});await loadData()}catch(e){alert('Could not delete: '+e.message)}};
$('scanBtn').onclick=async()=>{$('scanNote').textContent='Starting camera…';if(!('BarcodeDetector'in window)){$('scanNote').textContent='Barcode scanning is not supported by this browser. Type it manually.';return}try{const detector=new BarcodeDetector();const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const v=document.createElement('video');v.srcObject=stream;v.setAttribute('playsinline','');v.style.cssText='width:100%;margin-top:10px;border-radius:10px';$('scanNote').replaceChildren(v);await v.play();const scan=async()=>{try{const c=await detector.detect(v);if(c.length){$('barcode').value=c[0].rawValue;stream.getTracks().forEach(t=>t.stop());$('scanNote').textContent='Barcode captured.';return}}catch(e){}if(stream.active)requestAnimationFrame(scan)};scan()}catch(e){$('scanNote').textContent='Camera unavailable. You can type the barcode manually.'}};
setView(false);
